### ISSUE TITLE
BackHandler doesn't work for tvos

### ISSUE THREAD

**Issue by Tagir-A** [react-native-community/react-native-tvos#18]
When using the BackHandler as described in [RNTester](https://github.com/react-native-community/react-native-tvos/blob/849b24184b8a65d555fc55d54332b7dce0b309c4/RNTester/js/RNTesterApp.ios.js), the handler doesn't work and menu button press causes to exit the app.

React Native version:

System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 21.04 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.1 - /usr/local/bin/node
    npm: 6.4.1 - ~/n/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: npm:react-native-tvos@0.60.4-6 => 0.60.4-6 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Use the following code in any component
```
  componentDidMount() {
    BackHandler.addEventListener("hardwareBackPress", this.handleBack);
  }
  handleBack = () => {
    Alert.alert("It's a me, Mario");
  };
```
2. Press "menu" button on tvos
3. App exits, instead of showing alert

Describe what you expected to happen:
Cause alert to open and don't exit the app.

Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/HkmBbUkOH

**Comment by dlowder-salesforce** [comment]
It will work if you use the new `TVMenuControl` module correctly.  Look in `RNTester/js/RNTesterApp.ios.js` in the 0.60.4-6 branch to see the usage; the menu button should be enabled when pushing on the nav stack, and disabled when you get back to the bottom.

This module was added to satisfy Apple's requirement that repeated menu button presses should bring the user to the home screen.  Previously, RN apps for tvOS would permanently install a menu key gesture handler and prevent this from working.

**Comment by wouterds** [comment]
Hi,

I see this issue was closed, but want to confirm if this is a bug in the library or bug in my implementation. The weird thing is that the event triggers for AndroidTV but not for tvOS, the API is therefore behaving inconsistently across platforms.

This example repository can be used to reproduce the bug;
- https://github.com/wouterds/react-native-tv-example
- (don't forget to `cp .env.example .env`)

To reproduce the bug;
- click on  a detail item
- go back using the remote

On Android you will see this log:
**`LOG  [FocusService] Back button pressed ✅`**

On tvOS you won't see it.

**Comment by douglowder** [comment]
I ran your app and looked at the view hierarchy on tvOS when a detail item is being viewed.

Seems that you are using native navigation, and there is a `RNScreensNavigationController` on top of the main view controller for the root view. So what appears to be happening is that the menu key event is handled by `RNScreensNavigationController` and pops the detail view off the navigation stack.  `BackHandler` is not involved.

If you were using `BackHandler` for navigation,  you would need to call `TVMenuControl.enableTVMenuKey()` in order to get any menu key events at all.

Hope this helps :)

**Comment by douglowder** [comment]
That is correct -- the native stack navigator is implemented natively using view controllers in iOS/tvOS and Fragments in Android, and they do have some different behaviors.

Since the menu key is actually working to dismiss the view, is there some additional feature you are trying to implement that requires `BackHandler`? If you just need to know when the view is dismissed, you can put a blur listener on the screen being dismissed, for example.

**Comment by wouterds** [comment]
I would just expect the `BackHandler` to work the same on tvOS & AndroidTV, so when going back to receive the `hardwareBackPress` event on both tvOS and AndroidTV.

**Comment by douglowder** [comment]
If the stack navigator was implemented in JS (as `@react-navigation/stack` does), then indeed `BackHandler` would be used for back navigation. However, since you are using `@react-navigation/native-stack`, the implementation is in native code provided by `react-native-screens`, and that is using the native navigation view controllers for the stack.

In general, `BackHandler` does not work the same on different platforms -- in fact it was originally Android-only, since iOS does not have a back button in the same sense that Android does. I added a tvOS implementation since Apple TV does have such a button -- however native 3rd party modules like `react-native-screens` may override it.

**Comment by wouterds** [comment]
I see, thanks for clarifying. The thing that bothers me is that it does work for Android with this `@react-navigation/native-stack` & `react-native-screens` implementation. Would be nice if we could align that behaviour between tvOS & Android TV. The native navigation feels a lot more natural to me than the JS one and has some additional features which are handy that do not exist on the JS one.

Would love to chat a bit more on this and help with implementing if possible.

**Comment by jonathankiefer** [comment]
I understand this issue is referring to the Apple TV remote's menu button. But, what about the dedicated back button on the Apple TV "Siri Remote" (pictured below). Is there a way to override its default behavior of navigating back to the previous screen? The BackHandler's "hardwareBackPress" event doesn't appear to work.
![image](https://user-images.githubusercontent.com/10038122/234731663-60ef61ab-c77f-49dc-8f08-5adec09ed357.png)

**Comment by ali-sao** [comment]
So, has anyone found a way out?

**Comment by wielski** [comment]
I figured out how to catch back button with `@react-navigation/native-stack` / `react-native-screens`.
It's neccessary to add `UITapGestureRecognizer` to `RNSNavigationController`.
It could be easily found in rootViewController children.

Here is expo module for this purpose, it's quite simple and should be easy to rewrite to default rn stack.

```
// BackButtonHandlerModule.h
#import <RNScreens/RNSScreenStack.h>

// BackButtonHandlerModule.swift
import ExpoModulesCore

var disableMenuGestureRecognizers: [RNSNavigationController: UITapGestureRecognizer] = [:]
var disableMenuGestureActions: [RNSNavigationController: () -> Void] = [:]

extension UIViewController {
  func disableMenuButton(action: @escaping () -> Void) {
    disableMenuGestureActions[self as! RNSNavigationController] = action

    let disableMenuGestureRecognizer = UITapGestureRecognizer(
      target: self, action: #selector(doAction)
    )
    disableMenuGestureRecognizer.allowedPressTypes = [
      NSNumber(value: UIPress.PressType.menu.rawValue)
    ]
    view.addGestureRecognizer(disableMenuGestureRecognizer)

    disableMenuGestureRecognizers[self as! RNSNavigationController] = disableMenuGestureRecognizer
  }

  func enableMenuButton() {
    if let disableMenuGestureRecognizer = disableMenuGestureRecognizers[
      self as! RNSNavigationController]
    {
      view.removeGestureRecognizer(disableMenuGestureRecognizer)
      disableMenuGestureRecognizers.removeValue(forKey: self as! RNSNavigationController)
    }
    if disableMenuGestureActions[self as! RNSNavigationController] {
      disableMenuGestureActions.removeValue(forKey: self as! RNSNavigationController)
    }
  }

  @objc func doAction() {
    if let disableMenuAction = disableMenuGestureActions[self as! RNSNavigationController] {
      disableMenuAction()
    }
  }
}

public class BackButtonHandlerModule: Module {
  @objc public func fireEvent() {
    print("BackButtonHandlerModule: Back button pressed")
    self.sendEvent("onBackButtonPress")
  }

  public func findRNSNavigationControllers(_ controller: UIViewController)
    -> [RNSNavigationController]
  {
    var controllers: [RNSNavigationController] = []

    if let controller = controller as? RNSNavigationController {
      controllers.append(controller)
    }

    for subview in controller.children {
      controllers.append(contentsOf: findRNSNavigationControllers(subview))
    }

    return controllers
  }

  public func definition() -> ModuleDefinition {
    Name("BackButtonHandler")

    Events("onBackButtonPress")

    Function("setHandler") { () -> Bool in
      print("BackButtonHandlerModule: Set handler")
      var navigationControllers: [RNSNavigationController] = []
      EXUtilities.performSynchronously {
        if let window = UIApplication.shared.delegate?.window,
          let rootViewController = window?.rootViewController
        {
          navigationControllers = self.findRNSNavigationControllers(rootViewController)
        }
      }

      if navigationControllers.count > 0 {
        EXUtilities.performSynchronously {
          for navigationController in navigationControllers {
            navigationController.disableMenuButton(action: self.fireEvent)
            print("BackButtonHandlerModule: Disabled menu button")
          }
        }
        return true
      }

      return false
    }

    Function("clearHandler") { () -> Bool in
      print("BackButtonHandlerModule: Clear handler")
      var navigationControllers: [RNSNavigationController] = []
      EXUtilities.performSynchronously {
        if let window = UIApplication.shared.delegate?.window,
          let rootViewController = window?.rootViewController
        {
          navigationControllers = self.findRNSNavigationControllers(rootViewController)
        }
      }

      if navigationControllers.count > 0 {
        EXUtilities.performSynchronously {
          for navigationController in navigationControllers {
            navigationController.enableMenuButton()
            print("BackButtonHandlerModule: Enabled menu button")
          }
        }
        return true
      }

      return false
    }
  }
}
```
