### ISSUE TITLE
any support for asyncStorage?

### ISSUE THREAD

**Issue by ishaqashraf** [react-native-community/react-native-tvos#68]
when i installed react native asyncStorage and stored some data and then on debugger it shows me warning that tvOS not supporting storage it will be removed any point. 
any other way to persist state ? i tried redux-persist same error

**Comment by dlowder-salesforce** [comment]
asyncStorage does work, but the stored data will go away if the app exits.  Fortunately on a real TV device, this is a lot more rare than on a phone, but will still be an issue.  If the amount of data is small, it can still be stored in NSUserDefaults preferences.  Otherwise, you would have to use cloud storage.

From https://developer.apple.com/library/archive/documentation/General/Conceptual/AppleTV_PG/index.html ....

### Local Storage for Your App Is Limited

The maximum size for a tvOS app bundle 4 GB. Moreover, your app can only access 500 KB of persistent storage that is local to the device (using the NSUserDefaults class). Outside of this limited local storage, all other data must be purgeable by the operating system when space is low. You have a few options for managing these resources:

- Your app can store and retrieve user data in iCloud.
- Your app can download the data it needs into its cache directory. Downloaded data is not deleted while the app is running. However, when space is low and your app is not running, this data may be deleted. Do not use the entire cache space as this can cause unpredictable results.
- Your app can package read-only assets using on-demand resources. Then, at runtime, your app requests the resources it needs, and the operating system automatically downloads and manages those resources. Knowing how and when to load new assets while keeping your users engaged is critical to creating a successful app. For information on on-demand resources, see On-Demand Resources Guide.

This means that every app developed for the new Apple TV must be able to store data in iCloud and retrieve it in a way that provides a great customer experience.

**Comment by ishaqashraf** [comment]
thanks for the detailed explanation. NSUserDefaults is available in react native with the name of `Settings` . Settings serves as a wrapper for NSUserDefaults
https://reactnative.dev/docs/settings
