### ISSUE TITLE
Question:  Is this going to be official support of React native for tvos?

### ISSUE THREAD

**Issue by sureshsu** [react-native-community/react-native-tvos#9]
In official react native 0.60.5, I am unable to compile RN code for TVOS. Is this repo official one for AppleTV support?

**Comment by dlowder-salesforce** [comment]
From README.md: “Going forward, Apple TV support for React Native will be maintained here and in the corresponding react-native-tvos NPM package, and not in the core repo. This is a full fork of the main repository, with only the changes needed to support Apple TV.”

Note that at this time, we have only 0.60.4-based releases.

**Comment by stevengiraldo** [comment]
Hey @dlowder-salesforce, how could we have it for React Native 0.59.10?. Thanks

**Comment by dlowder-salesforce** [comment]
@stevengiraldo you could try https://www.npmjs.com/package/react-native-tvos/v/0.59.8-1

**Comment by stevengiraldo** [comment]
Works fine. But I'd like to contribute with a release for 0.59.10
is there a particular process to do that?
Thanks!

**Comment by dlowder-salesforce** [comment]
@stevengiraldo there isn't a well defined process yet.  Currently the process is manually selecting the exact commit for a particular core version, then cherry-picking just the commits needed to get tvOS working.  There are always merge issues since RN changes pretty quickly.

In having a look at core, it seems that 0.59.8 and 0.59.10 differ by just 14 commits, so having a release should be possible.

**Comment by dlowder-salesforce** [comment]
@stevengiraldo please try 0.59.10-2 -- that should give you everything in core 0.59.10 plus all tvOS fixes.

**Comment by stevengiraldo** [comment]
Hey, @dlowder-salesforce it works perfectly, thanks for the support.
